### ISSUE TITLE
[Database] Changing folder / namespace structure

### ISSUE THREAD

**Issue by nicolas-revel** [jeremy-nowak/starter-project#3]
In my opinion, you may want to move the code that is related to the configuration of the database outside the Model namespace. For example, you could move this code inside a Database namespace. Thus, all the code inside it would be related to the database configuration and all the stuff that gravitates around it. 
The Model namespace would be more suitable for entities or even repositories. Then, those entities and repositories use code that lives into the Database namespace.

The Database namespace could contain, just as an example :
- Database classes
- Entity mappers
- Entity managers
- Query builders

If you want, we can discuss the implementation of those in a separate issue.

**Comment by jeremy-nowak** [comment]
Hello, thank you for bringing up this improvement! Indeed, this will make my project clearer, more maintainable, and scalable over time. Your feedback is greatly appreciated, and I'm always open to suggestions for further enhancements.

I wanted to let you know that I've just patched the project with your advice. Please feel free to check it out, and if you have any more suggestions or feedback, I'd be happy to hear them. Thanks again for contributing to the project's improvement! 

Cheers!
